using System.Xml.Linq;
using Microsoft.AspNetCore.DataProtection.Repositories;
using Npgsql;

namespace ZamanTakasi.Web.Infrastructure;

/// <summary>
/// Web uygulamasının Data Protection anahtarlarını PostgreSQL'de kalıcı tutar.
/// NEDEN: ProtectedLocalStorage'daki oturum (JWT) bu anahtarlarla şifrelenir. Anahtarlar container
/// dosya sisteminde kalırsa her deploy'da değişir ve TÜM kullanıcılar çıkış yapmış olur.
/// EF/migration'a bağımlı olmamak için küçük, kendi tablosunu kendisi oluşturan bir depo (API'nin
/// "DataProtectionKeys" tablosundan AYRI: iki uygulamanın anahtar halkası karışmasın).
/// </summary>
public sealed class PostgresXmlRepository : IXmlRepository
{
    private const string Table = "WebDataProtectionKeys";
    private readonly NpgsqlDataSource _dataSource;

    public PostgresXmlRepository(NpgsqlDataSource dataSource) => _dataSource = dataSource;

    /// <summary>Tabloyu yoksa oluşturur (idempotent). Uygulama açılışında bir kez çağrılır.</summary>
    public static void EnsureTable(NpgsqlDataSource dataSource)
    {
        using var cmd = dataSource.CreateCommand(
            "CREATE TABLE IF NOT EXISTS \"" + Table + "\" (" +
            "\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "\"FriendlyName\" text NULL, " +
            "\"Xml\" text NOT NULL)");
        cmd.ExecuteNonQuery();
    }

    public IReadOnlyCollection<XElement> GetAllElements()
    {
        var list = new List<XElement>();
        using var cmd = _dataSource.CreateCommand("SELECT \"Xml\" FROM \"" + Table + "\" ORDER BY \"Id\"");
        using var reader = cmd.ExecuteReader();
        while (reader.Read())
            list.Add(XElement.Parse(reader.GetString(0)));
        return list;
    }

    public void StoreElement(XElement element, string friendlyName)
    {
        using var cmd = _dataSource.CreateCommand("INSERT INTO \"" + Table + "\" (\"FriendlyName\", \"Xml\") VALUES ($1, $2)");
        cmd.Parameters.AddWithValue(friendlyName ?? (object)DBNull.Value);
        cmd.Parameters.AddWithValue(element.ToString(SaveOptions.DisableFormatting));
        cmd.ExecuteNonQuery();
    }
}
